### ISSUE TITLE
{...this.props} removed from Input

### ISSUE THREAD

**Issue by joaoeffting** [leonardowf/react-simple-currency#10]
Hey there,

Why did you remove the {...this.props} from Input?
I was using it to pass onBlur and id for html input and now it crashes because this props are not being passed to the html Input when i use Simple Currency

**Comment by leonardowf** [comment]
I am really sorry about the inconvenience :(

The props spreading was removed because of react warnings discussed into https://github.com/leonardowf/react-simple-currency/issues/8

I've just released a new version contemplating onBlur parameters and Id, approving @wfuertes changes of https://github.com/leonardowf/react-simple-currency/pull/11

Feel free to propose a better approach for your scenarios

Sorry again for the trouble

**Comment by joaoeffting** [comment]
@leonardowf @wfuertes Tks!!! It was nothing that we couldn't work around. Thank you for the fast support. You guys were amazing <3
